### PR TITLE
Allow compilation with force-safe-string

### LINKED ISSUE #13: fails to build due to safe-string warnings
I got this while trying to go from `opam.1.2.0` to opam2, by install `opam-devel`.

I believe it's because I'm using `4.06.1+trunk+force-safe-string` since that makes the `String_val` macro expect a `const char*`, not `char*`, which it's not getting from ml_solver ... but I'm not 100% that's the correct diagnosis.

```
#=== ERROR while installing mccs.1.1+8 ========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p mccs
# path         /home/user/.opam/4.06.1+trunk+force-safe-string/build/mccs.1.1+8
# compiler     4.06.1+trunk+force-safe-string
# exit-code    1
# env-file     /home/user/.opam/4.06.1+trunk+force-safe-string/build/mccs.1.1+8/mccs-24530-ed04f4.env
# stdout-file  /home/user/.opam/4.06.1+trunk+force-safe-string/build/mccs.1.1+8/mccs-24530-ed04f4.out
# stderr-file  /home/user/.opam/4.06.1+trunk+force-safe-string/build/mccs.1.1+8/mccs-24530-ed04f4.err
### stderr ###
# [...]
# mccs_stubs.cpp:397:15: note: in expansion of macro ‘String_val’
#          dft = String_val(Some_val(Field(arg, 1)));
#                ^~~~~~~~~~
# mccs_stubs.cpp: In function ‘Solver ml2c_solver(value)’:
# /home/user/.opam/4.06.1+trunk+force-safe-string/lib/ocaml/caml/mlvalues.h:256:24: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
#  #define String_val(x) ((const char *) Bp_val(x))
#                        ~^~~~~~~~~~~~~~~~~~~~~~~~~
# mccs_stubs.cpp:438:23: note: in expansion of macro ‘String_val’
#        ret.lp_solver = String_val (Field (ml_solver, 1));
#                        ^~~~~~~~~~



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install opam-client 2.0.0
  ∗  install opam-devel  2.0.0
  ∗  install opam-solver 2.0.0
The following actions failed
  ∗  install mccs 1.1+8
```

### PR DESCRIPTION
**Pull request by dra27**
CI change and largescale conversion to `const char *`

Fixes #13

### CODE REVIEW

**Comment by dra27** [comment]
Travis seem to be gradually changing default Linux builds from Trusty to Xenial (makes sense, given that 14.04 is now EOL). However, I can't get the backends to build on 16.04: see https://travis-ci.org/dra27/ocaml-mccs/jobs/562538336#L2005-L2016. If anyone has any advice (it seems to be in some way GCC 5 related, then great). However, it's fine with GCC 7, so I've pushed a commit to force Travis to 18.04 instead.

None of that's related to this PR.

**Comment by dra27** [comment]
Hah - now temporarily stalled on https://github.com/ocaml/ocaml-ci-scripts/pull/305!

**Comment by XVilka** [comment]
The CI PR was merged, so it is possible to update this PR I think.

**Comment by AltGr** [comment]
Great, thanks!

**Comment by kit-ty-kate** [comment]
@AltGr would be possible to get a release of mccs with this fix for it to be compatible with the upcoming OCaml 4.10?

**Comment by dra27** [comment]
Before it’s released, 24735a6 wants reverting
